# Basic Config
baseURL = "https://blog.blakekjohnson.dev/"
languageCode = "en-us"
title = "Blake K Johnson"
theme = "hugo-ink"

# Enable syntax highlighting
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Summary Config
summaryLength = 40

[params]
	subtitle = "Software Engineer"
	mainSections = ["posts"]
	featherIconsCDN = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/blakekjohnson"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/blakekjohnson"

[taxonomies]
	tag = "tags"
